spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-in-hunza
    username: spring-in-hunza
    password: spring-in-hunza
    # driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
